default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['LOCAL_MYSQL_USERNAME'] %>
  password: <%= ENV['LOCAL_MYSQL_PASSWORD'] %>
  host: <%= ENV['LOCAL_MYSQL_HOST'] %>


development:
  <<: *default
  database: comic_app_development

test:
  <<: *default
  database: comic_app_test

production:
  <<: *default
  database: comic_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
