default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: comic_app_development
  adapter: mysql2
  username: <%= ENV['LOCAL_MYSQL_USERNAME'] %>
  password: <%= ENV['LOCAL_MYSQL_PASSWORD'] %>
  host: <%= ENV['LOCAL_MYSQL_HOST'] %>

test:
  <<: *default
  database: comic_app_test
  adapter: mysql2
  username: <%= ENV['LOCAL_MYSQL_USERNAME'] %>
  password: <%= ENV['LOCAL_MYSQL_PASSWORD'] %>
  host: <%= ENV['LOCAL_MYSQL_HOST'] %>

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
