default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2

development:
  <<: *default
  database: comic_app_development
  username: <%= ENV['LOCAL_MYSQL_USERNAME'] %>
  password: <%= ENV['LOCAL_MYSQL_PASSWORD'] %>
  host: <%= ENV['LOCAL_MYSQL_HOST'] %>

test:
  <<: *default
  database: comic_app_test
  username: <%= ENV['LOCAL_MYSQL_USERNAME'] %>
  password: <%= ENV['LOCAL_MYSQL_PASSWORD'] %>
  host: <%= ENV['LOCAL_MYSQL_HOST'] %>

production:
  <<: *default
  database: comic_app_production
  username: <%= ENV['PRODUCTION_MYSQL_USERNAME'] %>
  password: <%= ENV['PRODUCTION_MYSQL_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_MYSQL_HOST'] %>
