default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 4E8BtLEYmLfy
  host: localhost


development:
  <<: *default
  database: comic_app_development

test:
  <<: *default
  database: comic_app_test

production:
  <<: *default
  database: comic_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
